name: Auto-generate scripts

on:
  push:
    branches: [ main ]
    paths:
      - "generate/**"
      - ".github/workflows/**"

  schedule:
  - cron: "0 9 * * FRI"

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.17

    - name: "Jalankan tes generator"
      shell: bash
      run: |
        sudo bash ./test.sh 2>&1
      working-directory: generate

    - name: "Jalankan regenerasi script"
      shell: bash
      run: |
        sudo bash ./generate-all.sh 2>&1
      working-directory: generate

    - name: Generate tag name
      run: echo "TAG_NAME=$(date +%F-%H-%M)" >> $GITHUB_ENV

    - name: Release scripts
      uses: softprops/action-gh-release@v1
      with:
        files: block/*Indonesia.user.js
        name: Automatic script generation
        tag_name: ${{ env.TAG_NAME }}
        body: "Rilis ini berisi semua skrip yang disediakan oleh repositori ini.\n\nSilahkan lihat [halaman proyek utama](${{ github.server_url }}/${{ github.repository }}) untuk deskripsi skrip."
        body_path: generate/release/release.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 2
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
